### PR TITLE
add simple postprocessing

### PR DESCRIPTION
**Pull request by saromanov**
Hi!
I've just a made simple extension for removing excess symbolsfrom the result. For example
```python
name = HumanName("Mick (@mickjagger) Jagger")
print(name.nickname) # shows @mickjagger
```
With parameter "postprocessing", we getting clear nickname
```python
name = HumanName("Mick '@mickjagger' Jagger",postprocessing=True)
print(name.nickname) # shows mickjagger
```

Also, we can define own rule for removing symbols
```python
name = HumanName(".Mag-Judge Harwell G Davis, III")
name.apply_postprocessing(delete_symbols='.')
print(name.title) #shows Mag-Judge
```
What do you think?

### CODE REVIEW

**Comment by derek73** [comment]
Conceptually I support the idea of providing consumers of this code with a way to do custom stuff to the names it while still retaining the useful parts of the parser. I also think it's probably worthwhile for this code to provide a way to remove a set of symbols from names when you just want to remove some junk in them.

Your code doesn't actually prevent the symbols from being added to the internal lists, but instead just prevents them from displaying when using the property methods. So I think that the symbols would still appear with `list(hn)`, for example. Seems cleaner to keep them out of the lists in the first place.

There is a `post_process()` method that happens at the end of the name parsing. Would implementing support for something like the following be a better solution for a way to do custom stuff to the names? Currently you'd have to subclass and override `post_process()` to do the same thing. 

```python
import re
def remove_symbols(instance):
    for attr in instance:
        setattr(instance, attr, re.sub('@!&+*', '', getattr(instace, attr)))
  
name = HumanName("Mick '@mickjagger' Jagger", postprocessing_callback=remove_symbols)
```

Since you're dealing with a HumanName instance here, it requires you to understand a bit about what that is in order to loop through it and do stuff with the names. Maybe it would be better to do it in a `pre_process()`. Since we're still dealing with a single string at that point, you wouldn't need to know as much about the internals of how the parser works. 

```python
def remove_symbols(string):
    return ''.join([symbol for symbol in string if symbol not in '@!&+*'])
  
name = HumanName("Mick '@mickjagger' Jagger", preprocessing_callback=remove_symbols)
```

As for removing symbols, I would probably add a `self.remove_symbols = ""`, set it in `__init__()` and then just always remove any characters included in that string. Do it in the `post_process()` so that it doesn't break stuff like "Jack & Jill".

**Comment by saromanov** [comment]
Thank you for detailed response!
I tried to call with ```list(hn)``` and actually symbols not appeared
```python
name = HumanName(".Mag-Judge Harwell G Davis, III")
name.apply_postprocessing(delete_symbols='.')
print(list(name)) #[u'Mag-Judge', u'Harwell', u'G', u'Davis', u'III']
```
But now, its doesen't matter.
In general, if i understand you correctly, we need to delete method ```remove_symbols()``` and doing all of things in the method post_process(), with ```remove_symbols``` in ```__init__```. Then it will be looks like:
``` python
name = HumanName(".Mag-Judge Harwell G Davis, III", remove_symbols="")
name.post_process() #Here doing same thing as in the my method remove_symbols
```
This is right?
Howewer, as you wrote, another point,  doing it in ```pre_process``` before string will be parse. In this case, we can get correct results for example in this case:
```python
name = HumanName("Mick (mickjagger) Jagger")
print(name.as_dict()) #Correct response
```
We have correct response
```{u'last': u'Jagger', u'suffix': u'', u'title': u'', u'middle': u'', u'nickname': u'mickjagger', u'first': u'Mick'}```
But if we have corrupted string
```python
name = HumanName(",.Mick (mickjagger) Jagger")
print(name.as_dict())
```
we have a wrong response 
```{u'last': u'', u'suffix': u'', u'title': u'', u'middle': u'Jagger', u'nickname': u'mickjagger', u'first': u'.Mick'}```
Now middle is Jagger. If we would remove the symbols(".,") in the ```pre_process``` we could prevent this error.
So, now i even don't know thats better, apply method ```remove_symbols``` in ```pre_process``` or in ```post_process``` ?

**Comment by derek73** [comment]
In general the approach of this parser is to trust the input. If someone says their name is `Big.Kah00na!` we simply take those characters and put it into the right bucket depending on how/where it appears in the string. The only characters the parser cares about are ones that indicate various name parts, so far they are `,&()` and, of course, whitespace. There are only 3 supported variations of comma placement, so I think `,.Mick (mickjagger) Jagger` is not a case this parser needs to support. 

So I think the most the parser could do to clean up the input is provide some hooks for you to do things at various stages of parsing. Currently you could subclass `HumanName` but I agree that could be intimidating. If we want to provide easier tweaking I prefer the idea of passing in functions that could be used to do more than just remove characters. (maybe removing characters could be the example in the docs.) But I'm not sure what advantage that provides over just doing it outside of the parser, e.g. `HumanName("Mick (@mickjagger) Jagger".replace("@",""))`?

Removing a period at the beginning of name parts would be one place where a post-parsing hook would be handy, then you could look at each parsed name piece and strip off any leading periods, but you'd need to know how the parser works and the internal data structure. But automatically handling misplaced periods is tricky and beyond the scope of this library, there's too much variation in the mistake to write rules about how to correct it.

What is your dataset? What are you trying to do exactly with the parser? Which of the examples you provided are realistic examples from the input you are dealing with?

**Comment by saromanov** [comment]
Ok, i understood it.
Of course, user can doing post processing, but at the same time, i think that library also must provide tools for minimal post processing.
Example with ```HumanName("Mick (@mickjagger) Jagger".replace("@",""))``` is nice, but it need doing for each case(if such case is quite a bit). Even if doing something like
```python
def pre_processing(text, symbols=""):
     return ''.join([symbol for symbol in text if symbol not in symbols])

HumanName(pre_processing("Mick (@mickjagger) Jagger", symbols='@'));
```
user must to write snippet ```pre_processing```. Of course, this is not tricky, but not for very lazy people :)
I agree that this is can provide as example, and not in the main module.
    
I'm not have any special datasets, i'm just experementing with this library. Therefore, probably incorrect understand main idea. Because, as you said, your library works with "clean" data, but my idea was improve working with "raw" data.

**Pull request closed without merging**
