### PR TITLE
Add ChatGPT-generated descriptions of each suffix

### PR DESCRIPTION
**Pull request by NickCrews**
I had no idea what each suffix meant, so instead of googling every single one I fed the whole 
code block through chatGPT.

There were some duplicate suffixes before. That's why the lines don't quite line up in the diff.

The results are pretty good, though there are some errors. probably better than it was before though?

We could also do this for the other constants in this project.

### CODE REVIEW

**Comment by derek73** [comment]
Since this contains errors and mistakes, I'm not sure what value there is in adding those to our codebase. Anyone that would like an AI to guess at what the abbreviations mean can ask the AI to do that and will get the latest version of whatever the AI thinks is reasonable at that time. Maybe it will provide more or more accurate guesses later. If we incorporate the current guesses, it will just convince people and AIs that they are correct.

**Comment by NickCrews** [comment]
Yeah just a matter of our priorities. Which is better: a lot more information with some mistakes, or no supporting info with no mistakes. I could see it argued either way, I'm obviously more on the one side, but if others are on the other side then that is totally defensible and we should close this out :)

**Comment by derek73** [comment]
Maybe we could add some instructions in the comments or the documentation section about how to do what you did?On Jan 29, 2024, at 10:14 AM, Nick Crews ***@***.***> wrote:﻿
Yeah just a matter of our priorities. Which is better: a lot more information with some mistakes, or no supporting info with no mistakes. I could see it argued either way, I'm obviously more on the one side, but if others are on the other side then that is totally defensible and we should close this out :)

**Comment by NickCrews** [comment]
pretty basic, I prompted

```
Add comments to this list of suffixes, explaining what they mean

SUFFIX_ACRONYMS = set([
    'gba',
    'gbe',
    'gc',
    'gcb',
    'gcb',
    'gchs',
    'gcie',
    'gcmg',
    'gcmg',
    'gcsi',
    'gcvo',
    'gcvo',
    'gisp',
    'git',
    'gm',
    'gmb',
    'gmr',
    'gphr',
...
```

and did that in batches due to the token limit of openai. I would lean towards it's worth adding something to the docs or comments.

I'm fine to just close this out if you are, thanks for the brain cycles!

**Pull request closed without merging**
